apiVersion: v1
kind: Service
metadata:
  name: quotes-app-service
  labels:
    app: quotes-app
    tier: backend
    environment: dev
spec:
  selector:
    app: quotes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  #type: LoadBalancer
